{% set name = "fluentxy" %}
{% set version = "0.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  script: "flit install --python {{ PYTHON }}"
  noarch: python

requirements:
  host:
    - flit >=1.2,<2.0
    - python

  run:
    - python >=3.6,<4.0
    - pandas >=0.23
    - numpy >=1.11,<2.0
    - parse >=1.9,<2.0

test:
  requires:
    - pytest >=3.2.0
    - pytest-datadir >=1.3.0,<2.0
  imports:
    - fluentxy
  commands:
    - pytest --pyargs fluentxy -vv

about:
  home: https://github.com/bryanwweber/fluentxy
  license: BSD 3-Clause
  license_file: LICENSE
  license_family: BSD

  summary: "A small package to parse `.xy` output files from Fluent into Pandas DataFrames."
